/**
 * Regenerate public/firebase-messaging-sw.js with the Firebase web config for
 * THIS project. The web config is public (apiKey is not a secret), but it
 * can't be inlined by Next.js into a file under public/, so this script swaps
 * the placeholder object in the checked-in service worker.
 *
 *   NEXT_PUBLIC_FIREBASE_CONFIG='{"apiKey":"…","authDomain":"…","projectId":"…","messagingSenderId":"…","appId":"…"}' \
 *   npx tsx scripts/generate-firebase-sw.ts
 *
 * Only the FIREBASE_CONFIG object is rewritten — the message handler stays.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const SW_PATH = join(__dirname, '..', 'public', 'firebase-messaging-sw.js');
const START = '// __FIREBASE_CONFIG_START__ (regenerated by scripts/generate-firebase-sw.ts)';
const END = '// __FIREBASE_CONFIG_END__';

const raw = process.env.NEXT_PUBLIC_FIREBASE_CONFIG;
if (!raw) {
  console.error('NEXT_PUBLIC_FIREBASE_CONFIG is not set. Provide the Firebase web config JSON.');
  process.exit(1);
}

let config: Record<string, string>;
try {
  config = JSON.parse(raw);
} catch {
  console.error('NEXT_PUBLIC_FIREBASE_CONFIG is not valid JSON.');
  process.exit(1);
}

for (const key of ['apiKey', 'authDomain', 'projectId', 'messagingSenderId', 'appId']) {
  if (typeof config[key] !== 'string' || !config[key]) {
    console.error(`NEXT_PUBLIC_FIREBASE_CONFIG is missing the "${key}" field.`);
    process.exit(1);
  }
}

const sw = readFileSync(SW_PATH, 'utf8');
const startIdx = sw.indexOf(START);
const endIdx = sw.indexOf(END);
if (startIdx === -1 || endIdx === -1 || endIdx <= startIdx) {
  console.error('Could not locate the FIREBASE_CONFIG markers in firebase-messaging-sw.js.');
  process.exit(1);
}

const indent = '  ';
const block = `const FIREBASE_CONFIG = {
${indent}apiKey: '${config.apiKey}',
${indent}authDomain: '${config.authDomain}',
${indent}projectId: '${config.projectId}',
${indent}messagingSenderId: '${config.messagingSenderId}',
${indent}appId: '${config.appId}',
};`;

const next =
  sw.slice(0, startIdx + START.length) +
  '\n' +
  block +
  '\n' +
  sw.slice(endIdx);

writeFileSync(SW_PATH, next);
console.log(`Wrote ${SW_PATH} with project "${config.projectId}".`);
